//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public string Batch_id { get; set; }
        public string Batch_name { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<int> Scheme_id { get; set; }
    }
}
