//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Feedback_id { get; set; }
        public Nullable<int> Qn_id { get; set; }
        public Nullable<int> Substaffmap_id { get; set; }
        public string Username { get; set; }
        public Nullable<int> Option_id { get; set; }
    }
}
