//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_staff_mapping
    {
        public int Substaffmap_id { get; set; }
        public string Subject_id { get; set; }
        public string Staff_id { get; set; }
        public Nullable<int> Semester_id { get; set; }
    }
}
