//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjecy
    {
        public string Subject_id { get; set; }
        public string Subjectname { get; set; }
        public Nullable<int> Schemeid { get; set; }
        public Nullable<int> Semesterid { get; set; }
    }
}
